cgcb:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  # Crane Effort Controllers ---------------------------------------
  crane_x_effort_controller:
    type: effort_controllers/JointEffortController
    joint: planar_x

  crane_z_effort_controller:
    type: effort_controllers/JointEffortController
    joint: planar_z

  crane_rot_effort_controller:
    type: effort_controllers/JointEffortController
    joint: pelvis_joint

  # # Effort Controllers ---------------------------------------
  # hip_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: hip

  # lankle_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: left_ankle

  # rankle_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: right_ankle

EffPosCon:
  planar_x:
      params: {P: 2000.0, I: 0.0, D: 10.0}
  planar_z:
      params: {P: 2000.0, I: 0.0, D: 10.0}
  pelvis_joint:
      params: {P: 2000.0, I: 0.0, D: 10.0}
  # hip:
  #     params: {P: 200.0, I: 0.0, D: 1.0}
  # left_ankle:
  #     params: {P: 60.0, I: 0.0, D: 4.0}
  # right_ankle:
  #     params: {P: 60.0, I: 0.0, D: 4.0}
