simple_pole:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  
  # Effort Controllers ---------------------------------------
  pole_effort_controller:
    type: effort_controllers/JointEffortController
    joint: pole_axis

EffPosCon:
  pole_axis:
      params: {P: 120.0, I: 0.0, D: 10.0}
