tmj:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  
  # Effort Controllers ---------------------------------------
  spring_effort_controller:
    type: effort_controllers/JointEffortController
    joint: spring_axis

EffPosCon:
  spring_axis:
      params: {P: 100.0, I: 0.0, D: 0.0}
